##########################################################
###################  生产环境的profile  ###################
##########################################################
spring:
  profiles: prod
  kafka:
    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      bootstrap-servers: 39.108.185.51:9092
    consumer:
      zookeeper-connect: zookeeper:2181
      bootstrap-servers: 39.108.185.51:9092
      group-id: foo
      session-timeout: 6000
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer  
  datasource:
      url: jdbc:mysql://39.108.185.51:3306/prison_ywgk?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true
      username: root
      password: 3m4c3n9j!@##@
      filters: log4j,wall,mergeStat

logging:
  level.root: warn
  path: logs

host: http://39.108.185.51:8082/ywgk-app/